# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'


target 'FlyPig2.0' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlyPig2.0
	platform :ios, '13.0'
    pod 'OHMySQL'

  target 'FlyPig2.0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlyPig2.0UITests' do
    # Pods for testing
  end

end
